In [2]:
import numpy as np

## lets do some basic stuff

In [10]:
a = np.array(5)
a

array(5)

In [19]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
a = a.reshape(2,5,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [21]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(2, 5, 2)
3
20
int64


In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## some operation

In [25]:
a = np.array([20,30,40, 50])
b = np.arange(4)

In [26]:
b

array([0, 1, 2, 3])

In [27]:
a

array([20, 30, 40, 50])

In [35]:
c = a * b

In [38]:
c

array([  0,  30,  80, 150])

In [37]:
c > 50

array([False, False,  True,  True])

In [39]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])

## the end